- name: configuring frontend component
  hosts: frontend
  become: yes
  tasks:
    - name: enable and disable nginx
      ansible.builtin.command: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: enable namd start nginx 
      ansible.builtin.service:
        name: nginx
        enable: yes
        state: started

    - name: remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download frontend code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip 

    - name: extract frontend file
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: remove default nginx conf 
      ansible.builtin.file:
        src: /etc/nginx/nginx.conf
        state: absent

    - name: copy roboshop nginx conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted