- name: configuring mongodb server
  hosts: mongodb
  become: yes

  tasks:
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: installing mongodb from repo
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: enabling and starting the mongodb
      ansible.builtin.service:
        name: mongod
        enabled: yes
        state: started
        
    - name: allowing the remote access
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: restarting mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted

