- name: configure rabbitmq component
  become: yes
  hostes: rabbitmq
  tasks: 
    - name: copy rabbitmq repo
      ansible.builtin.copy:
        name: rabbitmq
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: installed
    
    - name: enable and start rabbitmq component
      ansible.builtin.service:
        name: rabbitmq-server
        enabled: true
        state: started

    - name: create rabbitmq setup user
      community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present