- name: configure shipping component
  become: yes
  hosts: shipping 
  tasks: 
    - name: install maven 
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - maven 
        - mysql

    - name: install PyMySQL and cryptography 
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - cryptography
        - PyMySQL
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: create roboshop syatem user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    
    - name: import the shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: extract shipping files
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: install maven dependencies
      ansible.builtin.commend: mvn clean packeage
      args: 
        chdir: /app
    
    - name: rename jar file
      ansible.builtin.commend: mv target/shipping-1.0.jar shipping.jar 
      args: 
        chdir: /app

    - name: copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
    
    - name: syatem daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable and start shipping component
      ansible.builtin.service:
        name: shipping
        enabled: yes
        state: started
    
    - name: import data from schemas
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.hellodevsecops.space
        state: import
        target: "{{ item }}"
      loop: 
        - /app/db/schema.sql
        - /app/db/app-user.sql 
        - /app/db/master-data.sql

    - name: restarting the shipping component
      andible.builtin.service:
        name: shipping 
        state: restarted
    
