- name: configuring user component
  hosts: user
  become: yes
  tasks: 
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y 

    - name: enableing nodejs module
      ansible.builtin.command: nf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory


    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    
    - name: download user code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
        dest: /tmp/user.zip

    - name: extract user file
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.npm:
        path: /app
    
    - name: copy user.service to system directory
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
          
    - name: user component enable and start
      ansible.builtin.service:
        name: user
        enabled: yes
        state: started
